[package]
name = "competitive-rust"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "leetcode_001"
path = "src/leetcode/problem_001_two_sum.rs"

[[bin]]
name = "beecrowd_1041"
path = "src/beecrowd/problem_1041_coordinates_of_a_point.rs"

[dependencies]
